baseURL = "https://nicolasbrosse.fr/blog/"
languageCode = "fr-FR"
title = "Nicolas Brosse - Pour commencer"
theme = "hugrid"
disableKinds = ["sitemap"]
enableRobotsTXT = "true"
defaultContentLanguage = "fr"

[params]
    # Meta
    title = "Nicolas Brosse"
    subtitle = "Les endroits où me trouver et les infos me concernant."
    author = "Nicolas Brosse"
    description = "Les autres endroits où me trouver sur internet."

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Allez voir"

    # Footer text
    footertext = "Site crée avec le [générateur de site statique Hugo](http://gohugo.io). Thème par [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/) et [aerohub](https://github.com/aerohub)"